version: 0.0
os: linux

files:
  - source: /
    destination: /opt/paylens/codedeploy
    overwrite: true

hooks:
  BeforeInstall:
    - location: deploy/codedeploy/before_install.sh
      timeout: 300

  AfterInstall:
    - location: deploy/codedeploy/after_install.sh
      timeout: 300

  ApplicationStart:
    - location: deploy/codedeploy/application_start.sh
      timeout: 600

  ValidateService:
    - location: deploy/codedeploy/validate_service.sh
      timeout: 300
